#include<iostream>
#include<cstring>
#include<cstdio>
#include<windows.h>
#include<conio.h>
#include<fstream>
#include<vector>
using namespace std;
ifstream fin("Beatmap.cbm");
void welcome_studio(){
	cout<<"-----------------------------------------------------";
	cout<<endl;
	cout<<"|                                                    |";
	cout<<endl;
	cout<<"|                                                    |";
	cout<<endl;
	cout<<"|                      made by                       |";
	cout<<endl;
	cout<<"|                     DT studio                      |";
	cout<<endl;
	cout<<"|                                                    |";
	cout<<endl;
	cout<<"|                                                    |";
	cout<<endl;
	cout<<"|                                                    |";
	cout<<endl;
	cout<<"|                    made with C++                   |";
	cout<<endl;
	cout<<"|                                                    |";
	cout<<endl;
	cout<<"|                                                    |";
	cout<<endl;
	cout<<"-----------------------------------------------------";
	cout<<endl;
	Sleep(3000);
	system("cls");
}
void start(){
	char i;
	cout<<"-----------------------------------------------------";
	cout<<endl;
	cout<<"|                                                    |";
	cout<<endl;
	cout<<"|            ==                       ==             |";
	cout<<endl;
	cout<<"|            C    P    P    I     C    G             |";
	cout<<endl;
	cout<<"|                        __                          |";
	cout<<endl;
	cout<<"|                       |__|                         |";
	cout<<endl;
	cout<<"|                       >|<                          |";
	cout<<endl;
	cout<<"|                        $                           |";
	cout<<endl;
	cout<<"|             Press the space to play                |";
	cout<<endl;
	cout<<"|                                                    |";
	cout<<endl;
	cout<<"|                                                    |";
	cout<<endl;
	cout<<"-----------------------------------------------------";
	cout<<endl;
	system("pause");
	system("cls");
}
char x[1000000];
int play(){
	cout<<"<^>"<<endl<<"Push your keyboard  if you see it!";
	getch();
	system("cls");
	cout<<"Perfect!"<<endl<<"You did it!";
	Sleep(900);
	system("cls");
	cout<<"<^>"<<" "<<"<^>"<<endl<<"and then,you will see the two duck (laugh)"<<endl<<"you should to click two key to kill them!";
	getch();
	getch();
	cout<<"Perfect!"<<" ";
	cout<<"Perfect!"<<" ";
	system("cls");
	cout<<"introduction is over now,you can go to have fun there now!";
	Sleep(800);
	system("cls");
	cout<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<endl<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" ";
	getch();
	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	cout<<"surprise! Happy April Fool's Day!"<<endl;
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
	Sleep(900);
	system("cls");
	Sleep(100);
		cout<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<endl<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" ";
	getch();
	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
	Sleep(900);
	system("cls");
	Sleep(100);	cout<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<endl<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" ";
	getch();
	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
	Sleep(900);
	system("cls");
	Sleep(100);	cout<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<endl<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" "<<"<^>"<<" ";
	getch();
	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
 	getch();
 	cout<<"Perfect!"<<" ";
	Sleep(900);
	system("cls");
	Sleep(100);
	system("pause");
	system("cls");
	return 0;
}
int main(){
	welcome_studio();
	start();
	play();
	return 0;
}
